### ISSUE TITLE
Mind hidden items in item label based focus

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-list-mixin#63]
List-mixin based components allow you to focus an item by typing the item's label or just the first letters of it: https://github.com/vaadin/vaadin-list-mixin/pull/50

If the list contains a `hidden` item it's possible to move the focus/roving tab index to it by using this feature. After this happens, the component cannot be tabbed back to as the roving tab index is assigned to an item that's not rendered.

Related to https://github.com/vaadin/vaadin-list-mixin/issues/51

**Comment by Haprog** [comment]
This has been fixed by #64
